---
- name: Install docker engine RedHat-based
  when: ansible_distribution == "CentOS"
  tags: install-docker
  block:
    - name: Install Docker packages
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Ensure Docker is started and enabled at boot
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
      ignore_errors: "{{ ansible_check_mode }}"

- name: Install docker engine Debian-based
  when: ansible_distribution == "Debian"
  tags: install-docker
  block:
    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

    - name: Ensure Docker is started and enabled at boot
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
      ignore_errors: "{{ ansible_check_mode }}"
