- name: Configuration Apache Kafka | Systemd unit
  tags: configure-kafka
  block:
    - name: Configuration Apache Kafka | Copy systemd files
      ansible.builtin.copy:
        src: "{{ role_path }}/files/systemd/kafka.service"
        dest: /etc/systemd/system/kafka.service
        owner: root
        group: root
        mode: 0644
    - name: Configuration Apache Kafka |Enable systemd Apache Kafka service
      ansible.builtin.systemd:
        name: kafka.service
        state: started
        enabled: true
