- name: Configuration Apache Zookeeper
  ansible.builtin.include_tasks: "{{ item_include }}"
  tags: configure-zookeeper
  vars:
    my_var: "{{ item_include }}"
  with_items:
    - generate-configuration.yaml
    - systemd-configuration.yaml
  loop_control:
    loop_var: item_include
