- name: Prepare system | Load OS type variables
  tags: preinstall
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yaml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}.yaml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yaml"
        - "{{ ansible_os_family | lower }}.yaml"
        - "{{ ansible_distribution | lower }}.yaml"
        - defaults.yaml
      paths:
        - "roles/preinstall/vars"
